# Site Settings
title: "Fitness Regime Hub"
description: "Transform your health journey with expert fitness guides, nutrition tips, workout plans, and wellness calculators. Your complete fitness regime hub."
url: "https://fithealthregimen-arch.github.io"
baseurl: "/fitness-regime-hub"

# Author Information
author:
  name: "Fitness Regime Hub Team"
  email: "info@fitnessregimehub.com"
  bio: "Your trusted source for fitness, nutrition, and wellness guidance."

# SEO Settings
lang: en_US
twitter:
  username: fitnessregimehub
  card: summary_large_image

logo: /assets/images/logo.png
social:
  name: Fitness Regime Hub
  links:
    - https://www.youtube.com/@FITLIFEREGIME
    - https://www.facebook.com/fitnessregimehub
    - https://www.instagram.com/fitnessregimehub

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
timezone: UTC

# Collections
collections:
  posts:
    output: true
    permalink: /:title/

# Pagination (disabled for now to simplify blog index under GitHub Pages)
# paginate: 6
# paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Tag Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Fitness Regime Hub Team"
      image: /assets/images/default-post.svg
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md

# Include
include:
  - _pages

# Site Navigation
navigation:
  - name: Home
    url: /
  - name: About
    url: /#about
  - name: Calculators
    url: /#calculators
  - name: Blog
    url: /blog/
  - name: Contact
    url: /#contact

# Categories for easy organization
categories:
  - Fitness
  - Nutrition
  - Wellness
  - Workouts
  - Weight Loss
  - Muscle Building
  - Cardio
  - Mental Health

# Social Media
social_media:
  youtube: "https://www.youtube.com/@FITLIFEREGIME"
  facebook: "#"
  instagram: "#"
  twitter: "#"
  linkedin: "#"
